### PR TITLE
Add JSON output for supported set of devices and their commands.

### PR DESCRIPTION
**Pull request by XerTheSquirrel**
Add JSON output for supported set of devices and their commands.

### CODE REVIEW

**Comment by xyzz** [comment]
what's the purpose of this change?

**Comment by XerTheSquirrel** [comment]
> what's the purpose of this change?

It is so that for the UI, for GPS, I can request all the supported devices, their dumping modes, and their VID/PID. This helps with auto-detection and the UI interface in general so that it knows what is supported.

**Comment by xyzz** [comment]
Ok we have a gui in the liveiso now, so closing

**Comment by XerTheSquirrel** [comment]
This could potentially still be used for automated scripting purposes.

**Pull request closed without merging**
