### PR TITLE
Add N703iD

### PR DESCRIPTION
**Pull request by grj1234**

### CODE REVIEW

**Comment by grj1234** [comment]
Thanks to @memory-hunter for finding the payload_base value for N703iD

**Comment by xyzz** [comment]
the payload_base is unused here by dump_nor, you should either remove it altogether or add another command which actually does make use of this field

**Comment by grj1234** [comment]
I added dump_nand command for N703iD, but it doesn't work due to unknown onenand_addr value

**Comment by xyzz** [comment]
Okay, I can merge it once you get it working and confirm it's dumping the nand correctly.

**Comment by Unabandonware** [comment]
This phone can be added as NOR only. Not sure how to update the pull request to fix that.
```
    Device("n703id", 0x0409, 0x01aa, {
        "dump_nor": NecMemoryDumper(base=0x0, size=MB(128)),
    }, payload_base=0x30000000, quirks=SLOW_READ),
```

**Comment by xyzz** [comment]
closing since the other one is merged now and there's no progress on this one

**Comment by grj1234** [comment]
I understand

**Pull request closed without merging**
