### PR TITLE
added phones

### PR DESCRIPTION
**Pull request by memory-hunter**
- some phones were confirmed dumped
- added comments to sectionalize phones with their make for neater organization

### CODE REVIEW

**Comment by memory-hunter** [comment]
@xyzz any complaints on this one?

**Comment by memory-hunter** [comment]
@xyzz updated the new devices.py and sorted according to generation, adding decorators and new models

**Comment by xyzz** [comment]
ok, two more things:
- there's no need to add comments with the name of device above every device since it's just duplicating the name that's already there
- what's the meaning of "PARTIAL NOR only" above some devices? I see they still have the dump_nand command

**Comment by memory-hunter** [comment]
I believe @Unabandonware wrote the Partial NOR only in case the NOR wasn't completely dumped or only the NOR is dumpable. Most of the newly added phones are modifications of the neighboring phones anyways so I would have to assume they are placeholders

**Comment by xyzz** [comment]
if the dump_nand command that's on there doesn't actually work then it should be removed altogether until it's properly figured out

**Comment by memory-hunter** [comment]
okay, all check

**Pull request merged**
